inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs

AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatString:
  EnforcedStyle: percent
